services:
  evm:
    build:
      context: ./evm
      dockerfile: Dockerfile
    container_name: evm-container
    working_dir: /app
    volumes:
      - ./evm:/app
      - ./shared_logs/evm:/app/logs
    command: /bin/bash -c "/app/entrypoint.sh"
    tty: true         # Keeps the container alive
    stdin_open: true  # Allows interactive terminal use
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - REPORT_GAS=true
    env_file:
      - .env

  non-evm:
    build:
      context: ./non-evm
    container_name: non-evm-container
    working_dir: /app
    entrypoint: ["/app/entrypoint.sh"]
    volumes:
      - ./non-evm:/app
      - ./shared_logs/non-evm:/app/logs
    tty: true         # Keeps the container alive
    stdin_open: true  # Allows interactive terminal use
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
      - SOLANA_URL=https://api.devnet.solana.com
    env_file:
      - .env
