version: '3.8'

services:
  evm:
    build:
      context: ./evm
      dockerfile: Dockerfile
    container_name: evm-container
    working_dir: /app
    volumes:
      - shared_input:/app/input
      - shared_logs_evm:/app/logs
      - evm_node_modules:/app/node_modules
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY:-}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY:-}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY:-}
      - REPORT_GAS=true
      - SOLC_VERSION=0.8.18
    healthcheck:
      test: ["CMD", "ls", "/app/input"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - smarthub-network

  non-evm:
    build:
      context: ./non-evm
      dockerfile: Dockerfile
    container_name: non-evm-container
    working_dir: /app
    volumes:
      - shared_input:/app/input
      - shared_logs_non_evm:/app/logs
      - ./non-evm/entrypoint.sh:/app/entrypoint.sh
      - ./non-evm/entrypoint-patch.sh:/app/entrypoint-patch.sh
      - rust_cargo_registry:/usr/local/cargo/registry
      - rust_cargo_target:/app/target
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
      - SOLANA_URL=https://api.devnet.solana.com
      - AWS_XRAY_SDK_ENABLED=false
      - CARGO_HOME=/usr/local/cargo
    healthcheck:
      test: ["CMD", "ls", "/app/input"]
      interval: 30s
      timeout: 10s
      retries: 3
    networks:
      - smarthub-network

  # File input service that makes the shared directory accessible to your backend
  file-input:
    image: alpine:latest
    container_name: file-input-service
    volumes:
      - shared_input:/data/input
    command: >
      sh -c "
        mkdir -p /data/input &&
        chmod -R 777 /data/input &&
        echo 'Input directory ready at /data/input' &&
        # Keep container running
        tail -f /dev/null
      "
    restart: unless-stopped
    networks:
      - smarthub-network

  # Permissions handler service - runs once to set up permissions
  permissions:
    image: alpine:latest
    volumes:
      - shared_input:/data/input
      - shared_logs_evm:/data/logs/evm
      - shared_logs_non_evm:/data/logs/non-evm
    command: >
      sh -c "
        mkdir -p /data/input /data/logs/evm /data/logs/non-evm &&
        chmod -R 777 /data/input /data/logs/evm /data/logs/non-evm &&
        echo 'All permissions set correctly' &&
        echo 'Input directory: /data/input' &&
        echo 'EVM logs directory: /data/logs/evm' &&
        echo 'Non-EVM logs directory: /data/logs/non-evm'
      "
    restart: "no"
    networks:
      - smarthub-network

volumes:
  shared_input:  # Docker-managed volume for input files
  shared_logs_evm:  # Docker-managed volume for EVM logs
  shared_logs_non_evm:  # Docker-managed volume for non-EVM logs
  evm_node_modules:  # Persistent volume for npm packages
  rust_cargo_registry:  # Persistent volume for Rust packages
  rust_cargo_target:  # Persistent volume for Rust build artifacts

networks:
  smarthub-network:
    driver: bridge
