version: '3.8'  # Adding explicit version

services:
  evm:
    build:
      context: ./evm
      dockerfile: Dockerfile
    container_name: evm-container
    working_dir: /app
    volumes:
      - ./evm:/app
      - ./shared_logs/evm:/app/logs
    command: bash -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - REPORT_GAS=true
    env_file:
      - .env

  non-evm:
    build:
      context: ./non-evm
      dockerfile: Dockerfile  # Explicitly specify Dockerfile
    container_name: non-evm-container
    working_dir: /app
    command: bash -c "chmod +x /app/entrypoint.sh && /app/entrypoint.sh"
    volumes:
      - ./non-evm:/app
      - ./shared_logs/non-evm:/app/logs
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
      - SOLANA_URL=https://api.devnet.solana.com
    env_file:
      - .env
