version: '3.8'

services:
  evm:
    build:
      context: ./evm
      dockerfile: Dockerfile
    container_name: evm-container
    working_dir: /app
    volumes:
      - ./shared/input:/app/input
      - ./shared/logs/evm:/app/logs
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - NODE_ENV=development
      - COINMARKETCAP_API_KEY=${COINMARKETCAP_API_KEY}
      - ALCHEMY_API_KEY=${ALCHEMY_API_KEY}
      - ETHERSCAN_API_KEY=${ETHERSCAN_API_KEY}
      - REPORT_GAS=true
    env_file:
      - .env

  non-evm:
    build:
      context: ./non-evm
      dockerfile: Dockerfile
    container_name: non-evm-container
    working_dir: /app
    volumes:
      - ./shared/input:/app/input
      - ./shared/logs/non-evm:/app/logs
      - ./non-evm/entrypoint.sh:/app/entrypoint.sh
      - ./non-evm/entrypoint-patch.sh:/app/entrypoint-patch.sh
    command: bash -c "chmod +x /app/entrypoint-patch.sh && /app/entrypoint-patch.sh && /app/entrypoint-wrapper.sh"
    tty: true
    stdin_open: true
    restart: unless-stopped
    environment:
      - RUST_LOG=debug
      - SOLANA_URL=https://api.devnet.solana.com
      - AWS_XRAY_SDK_ENABLED=false
    env_file:
      - .env
