[features]
seed = false
skip-lint = false

[programs.localnet]
placeholder_contract = "target/deploy/placeholder_contract.so"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[test]
startup_wait = 5000
shutdown_wait = 2000
upgrade_wait = 1000

[test.validator]
url = "https://api.devnet.solana.com"
clone = []
account = []
ledger = ""
